AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'test/**/*'
    - db/**/*
    - config/**/*
    - 'Gemfile'
    - 'Rakefile'
    - config.ru


Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'

# 2 spaces tab
Layout/IndentationStyle:
  Enabled: true
  IndentationWidth: 2
  EnforcedStyle: spaces
  SupportedStyles:
    - spaces
